### ISSUE TITLE
Fast Web View: Linearization and Flattening

### ISSUE THREAD

**Issue by rbovard** [py-pdf/PyPDF2#372]
Is there a way to create a PDF with parameter **Fast Web View** enabled?

**Comment by bdheeman** [comment]
I have not checked it, but you may see the logic behind **linearization** code at [qpdf](https://github.com/qpdf/qpdf) project.

**Comment by SDIdo** [comment]
Any updates on the matter?

**Comment by MartinThoma** [comment]
No, but feel free to submit a pr

**Comment by MartinThoma** [comment]
Some context: https://www.pdftron.com/blog/webviewer/how-build-fast-pdf-web-viewing/

**Comment by MartinThoma** [comment]
As this feature request didn't receive an update for a long time, I'm closing it.

I'm linking it in https://github.com/py-pdf/PyPDF2/discussions/1181 so that we don't forget about it. Please feel free to add more information here (PDFs that use it; other projects that implement it; explanations how it would improve PyPDF2). If we get closer to implementing it / have less open topics, I will re-open it :-)
