### ISSUE TITLE
A certain PDF File triggers OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by vershimajr** [py-pdf/PyPDF2#530]
Hello,

This [file](https://drive.google.com/open?id=1JduH56YX7nxFiRF25V8ZWwbyCa0IQvpv) is giving me trouble when attempting to simply create a PdfFileReader object

Code:
```
with open('./media/NTB - LOI.pdf', 'rb') as input:
  PyPDF2.PdfFileReader(input)
```

Error:

```
Traceback (most recent call last):
  File "<console>", line 2, in <module>
  File "/home/vershimaajo/gigarbox_academia/venv/lib/python3.6/site-packages/PyPDF2/pdf.py", line 1084, in __init__
    self.read(stream)
  File "/home/vershimaajo/gigarbox_academia/venv/lib/python3.6/site-packages/PyPDF2/pdf.py", line 1883, in read
    stream.seek(-11, 1)
OSError: [Errno 22] Invalid argument
```

Thanks for assistance!

**Comment by faridos** [comment]
i have the same issue also, when reading A3 pdf format.

**Comment by yanarof** [comment]
A temporary fix (so that you can use the program) would be to **re-write your file**, and then edit on this file. There are different ways of doing it:

print your ".pdf" to a new ".pdf" (0 loss of image quality)

OR

run the following command onyour pdf: `gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer -dNOPAUSE -dQUIET -dBATCH -sOutputFile="outputFile.pdf" "inputFile.pdf"`
I found this command [here](https://askubuntu.com/questions/113544/how-can-i-reduce-the-file-size-of-a-scanned-pdf-file/256449#256449), and the parameters are described [here](https://linux.die.net/man/1/gs). It helps make the pdf much smaller (depending on the quality you choose)

I guess that any other way of re-saving.

**Comment by vashek** [comment]
Same problem. I have identified the cause as an extra /Prev key in the trailer with the value 0. Technically, the PDF file is broken, but common software is able to work with it just fine. Unless there are other problems, it seems that a fix/workaround would be easy, except that this project is apparently dead, so I'll probably try to contribute the fix to PyPDF3 and/or PyPDF4 (assuming they have the same issue).
