### ISSUE TITLE
Enable GitHub Discussions?

### ISSUE THREAD

**Issue by sekrause** [py-pdf/PyPDF2#679]
GitHub has a feature called [Discussions](https://resources.github.com/devops/process/planning/discussions/) that enables a new space in the repository where people can ask questions about the project, make suggestion etc. without creating an issue. You can see an [example of Discussions in the psycopg repository](https://github.com/psycopg/psycopg/discussions).

You can also move an issue into a discussion. This could be a good way clear out the issue backlog because there are a lot of issues that are basically just questions asking for help (e.g. issues #589, #568, #620), those could all be moved into a discussion.

**Comment by MartinThoma** [comment]
Thank you for pointing that out! I've seen that in the settings, but I wasn't sure if the community wants it. Basically I was waiting for somebody to suggest it :smile: 

Here you are: https://github.com/py-pdf/PyPDF2/discussions/681

However, it might be that I don't follow many discussions as closely as I want to do with issues / PRs. Very generally speaking my priority would be dicussions < issues < PR on the long run. I hope we can get a lively community with active members like you so that this works out for everybody :-)
