### ISSUE TITLE
Sample_Code, Scripts and Tests are wrongly installed as top-level packages

### ISSUE THREAD

**Issue by mgorny** [py-pdf/PyPDF2#727]
The 2.7.2 release includes a regression where additional top-level packages are wrongly installed, e.g.:

```
/usr/lib/python3.10/site-packages/Sample_Code
/usr/lib/python3.10/site-packages/Scripts
/usr/lib/python3.10/site-packages/Tests
```

If these files are really supposed to be installed, they should be inside `PyPDF2` and not at top level.

**Comment by MartinThoma** [comment]
I'm pretty confused by that. This is how the diff between `1.26.0` and `1.27.2` looks like (of the source package):

![image](https://user-images.githubusercontent.com/1658117/162613182-a13340b1-ad4f-4123-afb8-dffa3629bb0a.png)

I've added Scripts, Sample_Code, and Tests because I have seen that they were present before. I don't know how they were added before, because they were neither in the Manifest nor there as packages.

Is this currently causing issues?

* I want to remove `Sample_Code` soon completely, see: https://github.com/py-pdf/PyPDF2/pull/726
* I don't like the Tests and Resources being added either and I have a hard time imagining that removing them would cause any trouble
* `Scripts` ... here I'm not sure how I should continue. Either I add them as a sub-package or I remove it. Is there another option?

**Comment by MartinThoma** [comment]
When I add it just to the manifest and not as a package, would that lead to the desired result?

**Comment by mgorny** [comment]
> I've added Scripts, Sample_Code, and Tests because I have seen that they were present before. I don't know how they were added before, because they were neither in the Manifest nor there as packages.

Yes, I suppose it makes sense to include them in sdist but they shouldn't be installed into site-packages. I'm afraid I can't help you figuring out why it worked before, setuptools sdist magic was always totally confusing to me (and I've seen that with my own packages too) but…

> When I add it just to the manifest and not as a package, would that lead to the desired result?

…yes, I think adding these directories to `MANIFEST.in` should achieve the desired result without causing them to be installed.

**Comment by MartinThoma** [comment]
I've just tried it out locally. Seems to do what is expected. I will make a release today (but probably not within the next 2 hours ... might be in the evening).

**Comment by mgorny** [comment]
Ok, thanks!

**Comment by mgorny** [comment]
I can confirm that 1.27.3 looks fine.
