### ISSUE TITLE
utils.PdfReadError ➔ errors.PdfReadError (Breaking Change in 1.27.6)

### ISSUE THREAD

**Issue by js-truework** [py-pdf/PyPDF2#779]
Filing this so that others who update a patch version of the repo and wonder why some lines broke will be able to find it:

In 1.27.6, all errors were moved to PyPDF2.errors (in commit https://github.com/py-pdf/PyPDF2/commit/1f0fbf3267d34aad3405b17deb461459ec26559e)

So if you were previously importing PdfReadError from PyPDF2.utils and are no longer able to, you need to change your import to get PdfReadError from PyPDF2.errors.

**Comment by MartinThoma** [comment]
Sorry 🙈 I haven't thought about the fact that people likely import it from there :see_no_evil: 

I think I'll create another version which additionally exposes it in utils. However, with PyPDF2 2.0 I want to move it there as the public interface. So `PyPDF2.errors` is definitely the way to go.

**Comment by MartinThoma** [comment]
I'm very sorry for the breaking change. I've just released 1.27.7 with https://github.com/py-pdf/PyPDF2/pull/780 that imports the Exceptions in utils so that peoples code will not break.

However, I do not explicitly re-export it from utils. I still want the exceptions to live in `PyPDF2.errors` on the long run. This is just a patch to avoid setups to break. Depending on the CI people might still get notes that they are using an implict export ([`mypy --no-implicit-reexport`](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-implicit-reexport))
